### ISSUE TITLE
Invalid manifest file generation

### ISSUE THREAD

**Issue by gicmo** [G-Node/nix-java#68]
I quote:
```bash
[WARNING] error reading /Users/gicmo/.m2/repository/org/g_node/nix-macosx-x86_64/1.1.0/nix-macosx-x86_64-1.1.0.jar; invalid manifest format
```
Which leads to:
```bash
λ ~/C/G/nj-test → java -jar target/nj-example-1.0-SNAPSHOT.jar
Writing to file
Exception in thread "main" java.lang.NoClassDefFoundError: org/g_node/nix/File
	at ck.iotest.main(iotest.java:13)
Caused by: java.lang.ClassNotFoundException: org.g_node.nix.File
	at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 1 more
```

**Comment by gicmo** [comment]
Problem seems to be the `./` in the `<Class-path>` tag.
This fixes it:
```diff
diff --git i/pom.xml w/pom.xml
index 6a6b80e..2ab91fc 100644
--- i/pom.xml
+++ w/pom.xml
@@ -149,7 +149,7 @@
                                     <addClasspath>true</addClasspath>
                                 </manifest>
                                 <manifestEntries>
-                                    <Class-Path>./ javacpp.jar ${project.artifactId}-linux-arm.jar
+                                    <Class-Path>. javacpp.jar ${project.artifactId}-linux-arm.jar
                                         ${project.artifactId}-linux-x86.jar ${project.artifactId}-linux-x86_64.jar
                                         ${project.artifactId}-windows-x86.jar ${project.artifactId}-windows-x86_64.jar
                                         ${project.artifactId}-macosx-x86_64.jar
```

**Comment by gicmo** [comment]
Actually looking at the `MANIFEST.MF` reveals a rather funny `Class-Path` Section:
```
Class-Path: . javacpp.jar nix-macosx-x86_64-linux-arm.jar

                             nix-macosx-x86_64-linux-x86.jar nix-macos
 x-x86_64-linux-x86_64.jar
                                        nix
 -macosx-x86_64-windows-x86.jar nix-macosx-x86_64-windows-x86_64.jar

                                        nix-macosx-x86_64-macosx-x86_6
 4.jar javacpp-1.1.jar jcip-annotations-1.0.jar
```

**Comment by gicmo** [comment]
Fixed.
